name: Build Docker Image

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push Docker image
        run: |
          cd helloworld
          docker build . --tag ghcr.io/Haran/helloworld:latest
          docker push ghcr.io/Haran/helloworld:latest
